# Generated by Django 5.0.6 on 2024-06-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoCloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
