# Generated by Django 5.0.6 on 2024-06-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoCloud', '0002_tareas_finalizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareasFinalizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('prioridad', models.CharField(max_length=10)),
            ],
        ),
    ]
